# Generated by Django 5.1.4 on 2025-05-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_sitesettings_delete_banner_remove_socialmedia_footer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='navbar_bg_color',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='title',
        ),
    ]
