# Generated by Django 5.1.4 on 2025-05-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_remove_sitesettings_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner',
            field=models.ImageField(default='static/img/image.jpg', help_text='banner image', upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='site logo ', null=True, upload_to='site_logo'),
        ),
    ]
