# Generated by Django 5.1.4 on 2025-05-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_alter_sitesettings_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='banner',
            field=models.ImageField(default='image.jpg', help_text='banner image', upload_to='banner'),
        ),
    ]
